config/routes.rb
Rails.application.routes.draw do
  root to: "urls#new"

  resources :urls, param: :small_url, only: %i[new show create] do
    get 'stats', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/url.rb
class Url < ApplicationRecord
  before_validation :parse_url

  validates :full_url, format: { with: /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?\z/ix }
  def to_param
    small_url
  end

  private

  def parse_url
    self.full_url = Domainatrix.parse(self.full_url).url
    self.full_url = "#{self.full_url}/" unless self.full_url.last == "/"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  # Show form url create
  def new
  end

  # Statistics
  def stats
    @url = Url.find_by!(small_url: params[:small_url])
  end

  # Show current url info
  def show
    url = Url.find_by!(small_url: params[:small_url])
    url.update(stats: url.stats + 1)
    redirect_to url.full_url, allow_other_host: true
  end

  # Create new url in DB
  def create
    full_url = params[:full_url]
    url_create = Url.create(full_url: full_url, small_url: create_small_url)
    
    if url_create.save
      flash[:url_m] = url_url(url_create)
      flash[:stats] = stats_url_path(url_create)
    else
      flash[:error_m] = "Что-то пошло не так, ссылка не создана("
    end

    redirect_to root_url
  end

  private

  def create_small_url
    SecureRandom.alphanumeric(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Play&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Shortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <div class="cont">
      <p class="main-title m-b-m s-t-p s-b-p"><%= link_to "Сервис по сокращению ссылок", root_path, class: "t-black link-clear" %></p>
    </div>
    <%= yield %>
  </body>
</html>

app/views/urls/new.html.erb
<div class="cont s-t-p s-b-p">
  <%= form_with url: urls_url, method: :post, data: {turbo: false} do |form| %>
    <%= form.label :full_url, "Введите полный url, который вы хотите сократить:", class:"main-title t-black" %>
    <%= form.text_field :full_url, class: "w-100 form-control mb-2" %>
    <%= form.submit "Сократить", class: "button button-red" %>
  <% end %>
</div>

<% if flash[:url_m].present? %>
  <div class="cont s-t-p s-b-p m-t-m">
      <% if flash[:info_m].present? %>
        <p class="main-title t-black m-b-m"><%= flash[:info_m] %></p>
      <% end %>
      <p class="main-title t-black m-b-s">
        Url создан: <a class="m-r-20 s-l-m text-info" href=<%= flash[:url_m] %> class="s-title"><%= flash[:url_m] %></a>
      </p>
      <p class="main-title t-black">
        <a class="text-info" href=<%= flash[:stats] %>>Статистика</a>
      </p>
  </div>
<% end %>

<% if flash[:error_m].present? %>
  <div class="cont s-t-p s-b-p m-t-m">
      <p class="main-title t-red"><%= flash[:error_m] %></p>
  </div>
<% end %>

app/views/urls/stats.html.erb
<div class="cont s-t-p s-b-p">
  <p class="main-title t-black m-b-m line">
    Полная ссылка:
    <a style="color:#FF3100;" href=<%= @url.full_url %>><%= fa_stacked_icon "link", base: "square-o" %></a>
    <div class="main-title t-red line copyFullUrl"><%= fa_stacked_icon "copy", base: "square-o" %></div>
  </p>

  <p class="main-title t-black m-b-m line">
    Краткая ссылка:
    <a style="color:#FF3100;" href=<%= url_url(@url.small_url) %>><%= fa_stacked_icon "link", base: "square-o" %></a>
    <div class="main-title t-red line copySmallUrl"><%= fa_stacked_icon "copy", base: "square-o" %></div>
  </p>

  <p class="main-title t-black b-b-m">
    Количество переходов по ссылке: <%= @url.stats %>
  </p>
  <p class="t-black">Совет: сохраните ссылку на статистику, чтобы не потерять</p>
</div>

<script>
    document.querySelector('.copyFullUrl')
    .addEventListener('click', function() {
        var copyText = "<%= @url.full_url %>"
        navigator.clipboard.writeText(copyText);
        alert("URL скопирован")
    })
</script>

<script>
    document.querySelector('.copySmallUrl')
    .addEventListener('click', function() {
        var copyText = "<%= url_url(@url.small_url) %>"
        navigator.clipboard.writeText(copyText);
        alert("URL скопирован")
    })
</script>